version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "sleep 5 && python manage.py makemigrations 
      && python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8080 --noreload"
    volumes:
      - .:/coded
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A mysite worker -l INFO
    volumes:
      - .:/coded
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - web
      - redis
      - db
  redis:
    image: redis
