# Generated by Django 4.0.3 on 2022-05-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profil_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
